.TH "SYSTEMSTATS" "1" "15 NOV 2022" "0.0.1"

.SH "NAME"
systemstats \- retrieves information about the host system

.SH "SYNOPSIS"
.HP \w'\fRsystemsStats\fR\ 'u
\fRsystemStatsz\fR [\-c\ \fIcpu usages\fR] [\-i \fIIP address\fR] [\-t\ \fITemperature\fR] [\-F\ \fICPU Usage\fR]
.br

.SH "DESCRIPTION"
.PP
\fB\-c\fR
.RS
  show current CPU Usage=##.##\% Used=##.#\%
.RE
.PP
\fB\-i\fR
.RS
  show host IPv4 address
.RE
.PP
\fB\-t\fR
.RS
  get current core temperature of system temp=## C
.RE
.PP
\fB\-F\fR
.RS
  show available cpu percentage and used cpu percentage freeCPU=##.#%, usedCPU=##.#%
.RE
.SH "NOTES"
THis script will be developed over time to display mor information using dfferent options

.SH "BUGS"
Bugs are cool but suggest bugs for me to squash (for developement)


.SH "AUTHORS"
Dante Whitworth-Ryan <modarrlock@gmail·com>
